#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  led,            sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  rightEnc,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftEnc,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  hEnc,           sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  armEnc,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  armOppEnc,      sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           leftDrive,     tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port3,           rightDrive,    tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port4,           hDrive,        tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port5,           armMain,       tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port6,           armOpp,        tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_5)
#pragma config(Motor,  port7,           clawServ,      tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// soupbot main.c usb 2018-09-12 hazel l <rose.hazel@protonmail.ch>

#include "drive.c"
#include "arm.c"
#include "auton.c"
#include "servo.c"

task teleoperated() {
	startTask(oi_vexNetMap);
	stopTask(basicDrive);
	startTask(drivePIDLoop);
	while(true) {} // fuck you
}
//565
//1235
//100 - arm
//435
//230
//1200

task main() {

	startTask(drive_init);
	startTask(arm_init);
	startTask(armServ_init);
	// DEBUG
	while(true) {
		if ((vexRT[Btn7L] == 1) && (vexRT[Btn7R] == 1)) {
			stopTask(teleoperated);
			startTask(autonomous);
		}
		if ((vexRT[Btn7U] == 1) && (vexRT[Btn7D] == 1)) {
			stopTask(autonomous);
			oi_arm_setPosition(0);
			startTask(teleoperated);
		}
	} // just wait forever
	//startTask(autonomous);
	//while(true) {}
}
